export const ENDPOINT = {
    users: 'me',
    users_password: 'me/update-password',
    sign_in: 'auth/login',
    register: 'auth/register',
    validateRecaptcha: 'auth/validate-recaptcha',
    contact: 'contact',
    licenses: 'license',
    robots: 'robot',
    robotsEnsambledUser: 'assembled-robot-by-user',
    robotEnsambledId: 'assembled-robot',
    strategy: 'strategy',
    addProduct: 'shopping-cart/add-item',
    shopping_cart: 'shopping-cart',
    promotionalCode: 'promotional-code',
    applyPromoCode: 'shopping-cart/apply-promotional-code',
    shopping_cart_delete: 'shopping-cart/delete-item',
    shopping_cart_update: 'shopping-cart/update-item',
    licenses_by_robot: 'license/find-by-robot',
    strategy_by_robot: 'strategy/find-by-robot'
};